// <auto-generated />
namespace Handin2_2_RDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Address5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Address5));
        
        string IMigrationMetadata.Id
        {
            get { return "201804020714575_Address5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
